services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  #  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'

  user_auth:
    build:
      context: ./backend/user-auth-service
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${USER_NAME_DB}
    volumes:
      - ./backend/user-auth-service/src:/app
    ports:
      - '8001:80'
    depends_on:
      - db
      #    - nginx

  payment_history:
    build:
      context: ./backend/payment-history-service
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${PAYMENT_HISTORY_NAME_DB}
    volumes:
      - ./backend/payment-history-service/src:/app
    ports:
      - '8002:80'
    depends_on:
      - db
      #    - nginx

  payment:
    build:
      context: ./backend/payment-service
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${PAYMENT_NAME_DB}
    volumes:
      - ./backend/payment-service/src:/app
    ports:
      - '8003:80'
    depends_on:
      - db
      #    - nginx

  rss_sites:
    build:
      context: ./backend/rss-sites-service
    env_file:
      .env
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${RSS_SITES_NAME_DB}
    volumes:
      - ./backend/rss-sites-service/src:/app
    ports:
      - '8004:80'
    depends_on:
      - db
      #    - nginx
      - kafka

  rss_saves:
    build:
      context: ./backend/rss-saves-service
    env_file:
      .env
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${RSS_SAVES_NAME_DB}
    volumes:
      - ./backend/rss-saves-service/src:/app
    ports:
      - '8005:80'
    depends_on:
      - db
      #    - nginx
      - kafka

  rss_generator:
    build:
      context: ./backend/rss-generator-service
    env_file:
      .env
    volumes:
      - ./backend/rss-generator-service/src:/app
    ports:
      - '8006:80'
    depends_on:
      - db
      #    - nginx
      - kafka

  rss_builder:
    build:
      context: ./backend/rss-builder-service
    env_file:
      .env
    volumes:
      - ./backend/rss-builder-service/src:/app
    ports:
      - '8007:80'
    depends_on:
      #    - nginx
     - kafka

  admin:
    build:
      context: ./backend/admin-service
    env_file:
      .env
    volumes:
      - ./backend/admin-service/src:/app
    ports:
      - '8008:80'
    depends_on:
      - db
      #    - nginx

volumes:
  postgres_data: