version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: $(DB_USERNAME)
      POSTGRES_PASSWORD: $(DB_PASSWORD)
      POSTGRES_DB: $(DB_NAME)
    ports:
      - '3456:3456'

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://kafka9092,OUTSIDE://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://localhost:9093
    ports:
      - '9093:9093'
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'

volumes:
  postgres_data: