
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper


  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'


  rss_sites:
   build:
     context: ./backend/rss-sites-service
   env_file:
     .env
   volumes:
     - ./backend/rss-sites-service/src:/app
   ports:
    - '8001:80'
   depends_on:
    - db
#    - nginx
    - kafka

  rss_generator:
   build:
     context: ./backend/rss-generator-service
   env_file:
     .env
   volumes:
     - ./backend/rss-generator-service/src:/app
   ports:
    - '8002:80'
   depends_on:
    - db
#    - nginx
    - kafka


volumes:
  postgres_data: